### ISSUE TITLE
安裝ionic的困難

### ISSUE THREAD

**Issue by bestian** [3dw/handbook#12]
如果遇到安裝困難請留言於此，請附上作業系統和錯誤碼

**Comment by linjason920523** [comment]
我在安裝Ionic時，不知試了幾次，還是一樣錯誤！
請問到底錯在哪裡?

>npm install -g cordova ionic
C:\Program
Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan\index.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program
Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\index.js:2:19)
    at Module._compile (module.js:570:32)
C:\Program
Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan\index.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program
Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\index.js:2:19)
    at Module._compile (module.js:570:32)

2017-02-02 18:24 GMT+08:00 Bestian Tang 唐宗浩 <notifications@github.com>:

**Comment by bestian** [comment]
i'm not sure nether.
不過可以試試這幾條路：

1. update node.js 至最新版
2. update npm 至最新版

    [update node&npm](https://docs.npmjs.com/getting-started/installing-node)

3 . 先裝cordova, 再裝ionic，看問題出在哪裡

`npm install cordova`
`npm install ionic`

在mac上如果需要管理員權限，則要再加上sudo當開頭
`sudo npm install cordova`
`sudo npm install ionic`

試試看吧
如果卡住再問問看~一起想辦法

**Comment by bestian** [comment]
如果作業系統是Windows
安裝完Node.js之後

不是從[命令提示字元]去開
而是從[Node command prompt]去開
才能正常使用npm

再試試看吧

[Node.js on Windows](https://www.google.com.tw/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwihyK6wv_fRAhWEmZQKHeXYCAkQFggbMAA&url=http%3A%2F%2Fblog.gvm-it.eu%2Fpost%2F20404719601%2Fgetting-started-with-nodejs-on-windows&usg=AFQjCNFtEdt62IU2Z4PK5jsIQQMCgtC5dw&sig2=mAplSPhLzvRUR4tXZp3qyg&cad=rja)

**Comment by linjason920523** [comment]
謝謝回覆，謝謝幫我解決這項問題

2017年2月5日 上午6:34，"Bestian Tang 唐宗浩" <notifications@github.com>寫道：

**Comment by linjason920523** [comment]
我重新安裝Node.js 後 可以安裝，但安裝到一半又出現npm ERR! cb() never
called!的錯誤字樣，我也有附上影片，請問到底出了哪些問題?
https://youtu.be/DNwLJgCH5ew

**Comment by bestian** [comment]
通常是把錯誤碼貼上google去查
剛查到[一篇相關的](https://github.com/npm/npm/issues/11378)
據說是把node.js本身升級，之後再跑一次就會好
試試看吧

**Comment by bestian** [comment]
還有一篇更詳細的step by step，可以試試看
[http://www.alex-arriaga.com/issue-when-running-npm-install-npm-err-cb-never-called-solved/](http://www.alex-arriaga.com/issue-when-running-npm-install-npm-err-cb-never-called-solved/)

**Comment by linjason920523** [comment]
謝謝幫我寫決問題！
我也試著使用npm install -g cordova ionic、npm install指令安裝完套件後，使用ionic
serve執行測試應用程式，發現發生錯誤。錯誤訊息:
C:\Users\linjason920523\Desktop\handbook-master\src>ionic serve
'ionic' 不是內部或外部命令、可執行的程式或批次檔。

我也試著使用Node.js控制台

C:\Users\linjason920523\Desktop\handbook-master\src>node
> ionic serve
ionic serve
      ^^^^^
SyntaxError: Unexpected identifier

請問到底錯在哪裡，為什麼找不到執行檔案?


2017-02-05 16:53 GMT+08:00 Bestian Tang 唐宗浩 <notifications@github.com>:

**Comment by bestian** [comment]
使用Node.js控制台
之後去專案根目錄（不是src）
本例中是C:\Users\linjason920523\Desktop\handbook-master>

在那裡再跑一次

`ionic serve`

看看

**Comment by linjason920523** [comment]
我也試過剛剛的方法，還是一樣的錯誤：
C:\Users\linjason920523\Desktop\handbook-master>dir
 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  44F3-1DDD

 C:\Users\linjason920523\Desktop\handbook-master 的目錄

2017/02/05  下午 02:21    <DIR>          .
2017/02/05  下午 02:21    <DIR>          ..
2017/02/04  上午 02:12               363 .editorconfig
2017/02/04  上午 02:12               481 .gitignore
2017/02/04  上午 02:12                21 .io-config.json
2017/02/04  下午 11:52                 8 cmd.bat
2017/02/04  上午 02:12             1,785 config.xml
2017/02/04  上午 02:12                85 ionic.config.json
2017/02/04  上午 02:12             1,210 LICENSE
2017/02/05  下午 04:47    <DIR>          node_modules
2017/02/04  上午 02:12             1,338 package.json
2017/02/04  上午 02:12             2,110 README.md
2017/02/04  下午 11:53    <DIR>          resources
2017/02/05  下午 04:59    <DIR>          src
2017/02/04  上午 02:12               465 tsconfig.json
2017/02/04  上午 02:12               178 tslint.json
2017/02/04  下午 11:53    <DIR>          www
              11 個檔案           8,044 位元組
               6 個目錄  206,260,281,344 位元組可用

C:\Users\linjason920523\Desktop\handbook-master>ionic serve
'ionic' 不是內部或外部命令、可執行的程式或批次檔。
C:\Users\linjason920523\Desktop\handbook-master>node
> ionic serve
ionic serve
      ^^^^^
SyntaxError: Unexpected identifier

2017-02-06 8:20 GMT+08:00 Bestian Tang 唐宗浩 <notifications@github.com>:

**Comment by bestian** [comment]
確定這回也是用Node command prompt進去的嗎?
它說
'ionic' 不是內部或外部命令、可執行的程式或批次檔。
表示ionic沒有裝成功，但上一則
SyntaxError: Unexpected identifier
是說有裝成ionic，只是不知道serve是什麼（去專案根目錄跑，即可解決這個問題）

兩則問題不一樣喔

試著
用Node command prompt進去
至
專案根目錄

再跑跑看
`ionic serve`
？

**Comment by linjason920523** [comment]
按照剛剛的說法使用Node cmd prompt 進去，
C:\Users\linjason920523\Desktop\handbook-master>ionic serve
'ionic' 不是內部或外部命令、可執行的程式或批次檔。

於是想要重新安裝，但是安裝過程又會出現cd never called!的字樣

C:\Users\linjason920523\Desktop\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

所以剩下為一辦法進去node執行環境測試：

> ionic serve
ionic serve
      ^^^^^
SyntaxError: Unexpected identifier

> ionic
ReferenceError: ionic is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

不管事serve還是ionic都會有undefined的錯誤
會不會是我這台電腦的問題?

Bestian Tang 唐宗浩 <notifications@github.com> 於 2017年2月6日 下午6:09 寫道：

**Comment by linjason920523** [comment]
有重新檢視一次步驟
使用cordova安裝是沒問題，可以當遇到ionic就會有問題

**Comment by dino0102** [comment]
upload 是不是被鎖了？我沒辦法上傳readme

**Comment by bestian** [comment]
請使用Github 上傳
upload是對於Ionic platform平台的。
