### ISSUE TITLE
為什麼安裝npm install -g cordova ionic 指令會出現錯誤?

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#15]
剛開始我使用
C:\>npm install -g cordova ionic
npm ERR! cb() never called!

到底哪裡有問題?

使用的環境也是node.js cmd prompt

**Comment by linjason920523** [comment]
我弟弟和我用的是同意型號的電腦，他的都安裝好了，為什麼我都都沒辦法安裝。
我重新試過安裝Node.js但都還是有問題。
C:\Users\linjason920523\Desktop\handbook-master\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

C:\Users\linjason920523\Desktop\handbook-master\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

C:\Users\linjason920523\Desktop\handbook-master\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

C:\Users\linjason920523\Desktop\handbook-master\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

C:\Users\linjason920523\Desktop\handbook-master\handbook-master>npm install -g cordova ionic
npm ERR! cb() never called!

**Comment by bestian** [comment]
如果貼錯誤碼上google，可以查到幾則有關的，可能要逐一測試
就像水管不通，可能問題會出在幾個環節，要逐一試過才能解決

升級node:
https://github.com/driftyco/ionic-cli/issues/936

清掉快取並重新安裝npm:
http://www.alex-arriaga.com/issue-when-running-npm-install-npm-err-cb-never-called-solved/


另，如果你弟弟的電腦裝好了，可以跑ionic serve
可以在他那邊裝一個github desktop，先在那邊測試與開發


另，手機的ionic view也可以先裝裝看，和電腦的環境是獨立的可以同時並進

**Comment by linjason920523** [comment]
感謝大家的協助！
重新安裝Node.js的  <strong>不穩定板</strong>後就可以使用了！
謝謝大家的幫忙！！
