### ISSUE TITLE
首頁圖片增加多樣性

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#16]
如果首頁每次只有那一張圖片那就太單調了
之後可以去免費圖庫抓一些圖片(或使用自己拍的)放到首頁
每次瀏覽都會顯示不同的圖片

**Comment by bestian** [comment]
可能要測一下UX
這不是網站，是手機app喔

增加多樣性可以用slideshow，不一定要用random image

**Comment by linjason920523** [comment]
如果真的要上傳圖片
需要壓縮圖片嗎?還是用原始畫質?

**Comment by linjason920523** [comment]
所以就是要讓圖片可以隨機撥放(上傳圖片後)
是每次開啟APP時重新選擇，還是固定時間移動會自動換圖片?

**Comment by bestian** [comment]
用Image resize的網路工具可把圖縮小
用ionic本身的slide元件來架就很理想了
http://ionicframework.com/docs/v2/components/#slides

**Comment by linjason920523** [comment]
我找到一篇關於這個提問的文章：https://www.djamware.com/post/58c78f0780aca7206976f167/how-to-create-autoplay-slides-using-ionic-2
他就出現在我的首頁推薦，不知道為什麼😐

**Comment by bestian** [comment]
你找的那篇是重頭架時用了
現在架到一半要改裝，要用的是這個
http://ionicframework.com/docs/v2/components/#slides

把鶵型做出來後，內容可以一起修改

**Comment by bestian** [comment]
發現放.gif是一個不比slide弱的好方法 ：）
