### ISSUE TITLE
圖示改良的可能

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#18]
介面圖示可以使用[http://material.io/icons](material.io/icons)的圖示會比較順眼

**Comment by bestian** [comment]
可以試試看
不過要確定離線也能看到喔。
ionic原本附的圖示不一定最漂亮，但可以確定離線也能看到。

總之，可以先把幾個圖示改掉，寫進去，測試後，commit上來吧!

**Comment by jeffandappy** [comment]
圖示不能只為了好看而已，需要更注重於簡單明瞭、一看即懂的要點，可想而知把這個軟體放到商店裡時，大多數的人第一個會先看到的是軟體的圖示，若圖示不能明瞭的話，不仔細看，或許不會有人知道這是什麼軟體。因此就會選擇從軟體選單中忽略。(這是其中的可能性)

**Comment by bestian** [comment]
原則上完全同意，但實際製作的部份呢？ @jeffandappy 要試試嗎？

**Comment by bestian** [comment]
看到新圖了，nice~
可能要用成splash的許多檔，放進resource資料夾才能開始測試它喔~
http://ticons.fokkezb.nl/

**Comment by linjason920523** [comment]
我先放好了隨機產生圖片的方法了，套用就可以用了！！！+1

**Comment by linjason920523** [comment]
可是我還不確定要隨機還是要單一圖片?

**Comment by bestian** [comment]
先看一下目前的單一動畫
