### ISSUE TITLE
驚喜箱流暢度提升可能

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#19]
把驚喜箱的顯示方法改進成快顯選單，範例[http://ionicframework.com/docs/v2/components/#action-sheets](http://ionicframework.com/docs/v2/components/#action-sheets)
這樣就不用多一個頁面

**Comment by bestian** [comment]
值得一試
UX上會更快
但是會不會一樣很有趣要試試看
可以先架actionsheet在「按我」的功能上
但先不要拆掉fabs部件
都測過再決定

**Comment by bestian** [comment]
有一點難度喔，要把相關的物件串列設定好才會運作，
@linjason920523 
要當練習題，試試看嗎?
https://ionicframework.com/docs/v2/components/#action-sheets

**Comment by linjason920523** [comment]
我已在程式碼中放入Choose(e)的方法，裡面有ActionSheet的範本以及程式庫都Import好了，也以在那裏參考....。_幸好沒有刪掉gotoFlag(e)_

**Comment by bestian** [comment]
great，後續的部份我把它架起來了
可以進程式碼，看看我加的部份，或許對未來要架ionic&ng2的部件時，會有幫助
