### ISSUE TITLE
無止盡的Building

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#20]
當我更改文件後伺服器會自動更新並顯示Building...(仔入圈圈)
然後等了一小時就是沒改變，重新仔入後也沒更新。
是我電腦太爛跑太久，還是發生建置錯誤?
SOS!!!

**Comment by bestian** [comment]
可能要去命令列看錯誤訊息
有的錯誤訊息不會顯示在瀏覽器上

如果有的話，可以先試著除錯
除錯不掉的話

可以把單次的commit都取消(discard)掉
回到本次剛同步進來的版本，重新來過
