### ISSUE TITLE
有甚麼推薦編輯器來開發ionic?

### ISSUE THREAD

**Issue by linjason920523** [3dw/handbook#24]
想請教大家，都是在使用哪種編輯器來開發ionic?
因為我平時就是使用notepad++，不知道有甚麼更好的編輯器或是大家平時在使用的編輯器來推薦。
:)

**Comment by bestian** [comment]
sublime text或atom.
我目前是用sublime text，試用版，免費

**Comment by ljcucc** [comment]
我現在找到VSCode(Visual Studio Code，也有人稱作Code)，支援angular框架的編輯器。不錯用，而且是用Electron 做的(cross-platform)。
