### ISSUE TITLE
離線時從近端拿到備用資料

### ISSUE THREAD

**Issue by bestian** [3dw/handbook#4]
修offline-handbook provider & page2.ts

**Comment by linjason920523** [comment]
離線操作??因該可以用web storage api
[https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

**Comment by bestian** [comment]
move to:
https://github.com/3dw/handbook/issues/13
