### ISSUE TITLE
app主要圖示設計

### ISSUE THREAD

**Issue by bestian** [3dw/handbook#5]
設計app的主要圖示

**Comment by linjason920523** [comment]
這裡有講道如何設計很好看又順眼的圖示
[點我進入](https://material.io/guidelines/style/icons.html)

**Comment by bestian** [comment]
看了，的確很棒。
最近我要忙網站更新，所以圖示設計會依milestone等五月再投入
@linjason920523 有興趣可以先跑這塊。

**Comment by jeffandappy** [comment]
我再圖片區放入了app icon-170318.png作為Apps的插圖圖示。不知那圖示是否符合程式內容的主題。

**Comment by bestian** [comment]
在萌典松，這張圖被改良後，選為封面及主要圖示了！horray!
