### ISSUE TITLE
選測Font-family

### ISSUE THREAD

**Issue by bestian** [3dw/handbook#9]
I'm not familiar with css font-families.
anyone can help?

**Comment by linjason920523** [comment]
這裡有個網站[https://fonts.google.com](Google Font)
只要幾行HTML就可以改文字樣式

**Comment by jeffandappy** [comment]
font family的使用方法：
font-family:你的字體;

則「你的字體」可以替換為自己想用的字體名稱。(建議使用網頁安全字體較安全些)

**Comment by bestian** [comment]
語法我知道，但目前沒空去選字體和測試
`ionic serve --lab`
可以同時測ios, andrid, windows

如果認領一下這項
直接把喜歡的字體加上去
確認在三個平台上字體顯示都ok的話
會很感謝
